# Generated by Django 4.2.5 on 2023-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_avatar_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.IntegerField(default=1699108781),
        ),
    ]
